### ISSUE TITLE
[Navbar] Polish

### ISSUE THREAD

**Issue by danielle-dsouza** [cusec/2023#13]
To Do
- [x] Align nav items left
- [x] Add `Sign up (Join us???)` button

Current:
<img width="1196" alt="Screen Shot 2022-09-02 at 9 15 18 AM" src="https://user-images.githubusercontent.com/42760127/188153898-32b6f68d-3943-4333-86bb-6e3ecdfe25c8.png">

Desired:
<img width="1220" alt="Screen Shot 2022-09-02 at 9 15 39 AM" src="https://user-images.githubusercontent.com/42760127/188153955-7c9c3c61-4c29-4d43-803d-a53ae0726b27.png">

**Comment by danielle-dsouza** [comment]
Update from https://github.com/cusec/2023/pull/12 - once this merges, we'll also have to move the circles below the navbar so they don't overlap with the nav items.

**Comment by HakimSkaik** [comment]
What will happen to the sign up button once the screen is minimized to mobile view?

**Comment by danielle-dsouza** [comment]
I made a sidenav when using mobile. So the button needs to be added to the list of options. Note that the home page looks really wack in mobile right now, but we'll manage that in separate tickets.

<img width="374" alt="Screen Shot 2022-09-06 at 3 17 55 PM" src="https://user-images.githubusercontent.com/42760127/188720405-c80f9730-fc5e-41bc-b48f-abcd879b949c.png">
