### ISSUE TITLE
[Landing] Change the font colour on card

### ISSUE THREAD

**Issue by danielle-dsouza** [cusec/2023#23]
The text on the card is not readable. 
<img width="753" alt="Screen Shot 2022-09-10 at 8 51 51 AM" src="https://user-images.githubusercontent.com/42760127/189484201-87e130a6-dcaa-453d-b128-f8cec788a6b1.png">

The colour should have greater contrast to background.

**Comment by HakimSkaik** [comment]
![Image](https://user-images.githubusercontent.com/98859282/190035693-1eb7456e-a745-4b8a-8a37-9669492b1a39.png)

Does this colour look good?

**Comment by danielle-dsouza** [comment]
Yep let's go with that for now! We can show it to UX during the next tech sync.

**Comment by danielle-dsouza** [comment]
Fixed in #30
