### ISSUE TITLE
[Impact Section] Add interactive background

### ISSUE THREAD

**Issue by danielle-dsouza** [cusec/2023#4]
<img width="836" alt="Screen Shot 2022-07-27 at 11 53 58 PM" src="https://user-images.githubusercontent.com/42760127/181416781-6c80fe53-5c21-4be8-899f-6bcbd6077cc7.png">

Idea:

- [ ] On mouseover (?) this purple masterpiece "waves"

**Comment by danielle-dsouza** [comment]
Blocked while we wait for GIF

**Comment by HakimSkaik** [comment]
@danielle-dsouza are we not handling this issue Afterall?

**Comment by danielle-dsouza** [comment]
@HakimSkaik I'd like for us to do this! If you have the bandwidth, feel free to take it on - I just don't have the time for it right now 😞
