### ISSUE TITLE
[Home] Replace dummy images

### ISSUE THREAD

**Issue by danielle-dsouza** [cusec/2023#41]
Follow up to #38

**Comment by HakimSkaik** [comment]
do we have the images yet?

**Comment by danielle-dsouza** [comment]
> do we have the images yet?

Nope ☹️. You can try reaching out to Charmaine or David about these.

**Comment by HakimSkaik** [comment]
So I reached out, Melissa told me they're on the doc? But I wasn't added to any google docs...

**Comment by danielle-dsouza** [comment]
Weird, I haven't been added either 🤔 . I looked through the google drive but I'm not sure which folder to look in so I'll DM Charmaine or David and let you know what they say.

**Comment by danielle-dsouza** [comment]
Added myself to this to remind me to follow up with them about the images!

**Comment by danielle-dsouza** [comment]
Charmaine sent a link in the discord!

**Comment by danielle-dsouza** [comment]
Just following up on this! We have a tentative deadline for Oct 29th (site needs to go live on the 30th) so checking in on how progress is going!

**Comment by HakimSkaik** [comment]
Hey! Thanks for checking in! I'm almost done I'm just trying to find some images for the "what is CUSEC" section

**Comment by danielle-dsouza** [comment]
Closed by #76
