### ISSUE TITLE
[Home] Change button styles

### ISSUE THREAD

**Issue by danielle-dsouza** [cusec/2023#45]
The `Join us` and `Sponsor` buttons need to be changed.

The new versions are:

https://user-images.githubusercontent.com/42760127/192169250-85467837-022f-40e5-aa96-7b477ed7ca58.mov

**Comment by HakimSkaik** [comment]
Does the card color change as well? Because the background color of the button is more grey?

**Comment by HakimSkaik** [comment]
What it looks like after changes:
https://user-images.githubusercontent.com/98859282/193278296-1758ac11-71b9-4f77-9410-ef48299bc421.mp4

is it up to the standards?
