### ISSUE TITLE
[Sponsor] Add Sponsor section

### ISSUE THREAD

**Issue by danielle-dsouza** [cusec/2023#47]
## Desktop

This appears after the `What is CUSEC` section. Check the figma for more details.
<img width="631" alt="Screen Shot 2022-09-25 at 8 00 38 PM" src="https://user-images.githubusercontent.com/42760127/192171602-14ccfa11-78a2-4871-809c-4e62e6c3c2b5.png">

## Mobile

This appears after the `Objective` section. Check the figma for more details.
<img width="383" alt="Screen Shot 2022-09-25 at 7 59 08 PM" src="https://user-images.githubusercontent.com/42760127/192171537-571ce50c-e1cb-405e-8063-7eaeda2072f5.png">

Both show a different number of sponsors. Speak with the sponsor team to get the right number and all the relevant logos.

**Comment by khathepham** [comment]
Hello! Sponsor team here!

I've uploaded the logos we have so far into the Technology Google Drive.

I doubt we'll have enough sponsors to warrant a horizontal scroll page, but one thing to keep in mind is that logo size will be dependent on sponsorship tier. if Bronze is 1x, then silver 1.5x, gold 2x, for example. (Not exact numbers but y'know what I mean).

https://2019.cusec.net/sponsors
http://2020.cusec.net/#/#sponsors 
https://2021.cusec.net/sponsors 
https://2022.cusec.net/#sponsors
