### ISSUE TITLE
[About] Update

### ISSUE THREAD

**Issue by danielle-dsouza** [cusec/2023#51]
Rework for `desktop`.

### Current
<img width="652" alt="Screen Shot 2022-09-10 at 8 41 05 AM" src="https://user-images.githubusercontent.com/42760127/189483821-64bbe5e2-11a6-4d1c-a0fc-3a51edc0b079.png">

### Desired
<img width="783" alt="Screen Shot 2022-09-25 at 8 16 26 PM" src="https://user-images.githubusercontent.com/42760127/192172341-6d971da1-9b8c-4551-925a-70879d4e0ee0.png">

**Comment by HakimSkaik** [comment]
regarding the about section, which of the homepage sections should it fall into? So I could have an idea of how to set the path

**Comment by danielle-dsouza** [comment]
It's still on the main url `/` if that's what you mean 🤔. Regarding where on the home page, it's beneath the `Impact` section and above the `Sponsors` section. You can check out the figma for more details! https://www.figma.com/file/Bm6J9yho3QXlfpUu4fyk0k/CUSEC-2023

**Comment by danielle-dsouza** [comment]
Closed by #69
